In [1]:
import os
import json
import numpy as np
import pandas as pd
from natsort import index_natsorted, order_by_index

In [12]:
FILE_PATH = './data/retweets/Eng/'
files = os.listdir(FILE_PATH)
retweet = pd.read_csv(FILE_PATH+files[0], error_bad_lines=False,)
for i in range(1,len(files)):
    temp = pd.read_csv(FILE_PATH+files[i], error_bad_lines=False)
    retweet = pd.concat([retweet, temp], ignore_index=True)

C:\Users\aruba\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3146: DtypeWarning: Columns (3,4,7) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
C:\Users\aruba\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3146: DtypeWarning: Columns (4) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
C:\Users\aruba\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3146: DtypeWarning: Columns (3,7) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
C:\Users\aruba\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3146: DtypeWarning: Columns (3) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

In [49]:
retweet.shape

(729309, 20)

In [22]:
df = retweet.reindex(index=order_by_index(retweet.index, index_natsorted(retweet['user_id'])))
df.head()

,text,is_qoute_status,in_reply_to_status_id,favorite_count,created_at,time,in_reply_to_screen_name,retweet_count,id_str,hashtags,symbols,lat,lon,place,country,lang,contributors,user_mentions,user_id,Unnamed: 19
446625,Lol porky is mad ....... yikes. https://t.co/y...,True,None,9,20201103,0109,None,1,1323432106547183616,[],[],NaN,NaN,NaN,NaN,en,None,[],0Voter2,NaN
288730,@GovernorTomWolf I’ve lived my life Normal thr...,False,1323339092189433868,3,20201102,1923,GovernorTomWolf,1,1323344879548813312,[],[],NaN,NaN,NaN,NaN,en,None,['GovernorTomWolf'],0_1776,NaN
13148,Remember that time BLM were all arrested for d...,True,None,330,20201102,0920,None,124,1323193131844673537,[],[],NaN,NaN,NaN,NaN,en,None,[],0_politics2,NaN
18181,Remember that time BLM were all arrested for d...,True,None,332,20201102,0920,None,125,1323193131844673537,[],[],NaN,NaN,NaN,NaN,en,None,[],0_politics2,NaN
23815,Remember that time BLM were all arrested for d...,True,None,336,20201102,0920,None,126,1323193131844673537,[],[],NaN,NaN,NaN,NaN,en,None,[],0_politics2,NaN

In [36]:
df = retweet.drop_duplicates(subset='id_str', keep='last')
df = df.reindex(index=order_by_index(df.index, index_natsorted(df['user_id'])))
df.head()

,text,is_qoute_status,in_reply_to_status_id,favorite_count,created_at,time,in_reply_to_screen_name,retweet_count,id_str,hashtags,symbols,lat,lon,place,country,lang,contributors,user_mentions,user_id,Unnamed: 19
446625,Lol porky is mad ....... yikes. https://t.co/y...,True,None,9,20201103,0109,None,1,1323432106547183616,[],[],NaN,NaN,NaN,NaN,en,None,[],0Voter2,NaN
288730,@GovernorTomWolf I’ve lived my life Normal thr...,False,1323339092189433868,3,20201102,1923,GovernorTomWolf,1,1323344879548813312,[],[],NaN,NaN,NaN,NaN,en,None,['GovernorTomWolf'],0_1776,NaN
572665,Remember that time BLM were all arrested for d...,True,None,444,20201102,0920,None,168,1323193131844673537,[],[],NaN,NaN,NaN,NaN,en,None,[],0_politics2,NaN
299161,Citizen it appears you are starving here is ...,True,None,1859,20201031,0434,None,357,1322396564258758656,[],[],NaN,NaN,NaN,NaN,en,None,[],0ddette,NaN
728409,Prole Citizen place on your face mask and shie...,False,None,35,20201103,1330,None,5,1323618630484086784,[],[],NaN,NaN,NaN,NaN,en,None,[],0ddette,NaN

In [52]:
df.to_csv('./output/filtered/retweet_text.csv',sep=',',index=False)

In [6]:
TWEET_PATH = './output/filtered/'
COMBINED = '/combined_vaccine.csv'
MASK = '/masking.csv'
filtered_files = os.listdir(TWEET_PATH)
vaccine_file =  pd.read_csv(TWEET_PATH + filtered_files[0] + COMBINED)
mask_file =  pd.read_csv(TWEET_PATH + filtered_files[0] + MASK)
for i in range(1,len(filtered_files)):
    temp1 = pd.read_csv(TWEET_PATH+filtered_files[i]+COMBINED, error_bad_lines=False)
    temp2 = pd.read_csv(TWEET_PATH+filtered_files[i]+MASK, error_bad_lines=False)
    vaccine_file = pd.concat([vaccine_file, temp1], ignore_index=True)
    mask_file = pd.concat([mask_file, temp2], ignore_index=True)

In [9]:
vaccine_file.shape, mask_file.shape

((69936, 16), (133194, 16))

In [10]:
vaccine_file.head()

,date,user,is_retweet,is_quote,text,quoted_text,lat,long,hts,mentions,tweet_id,likes,retweets,replies,quote_count,original_tweet_id
0,2020-11-02 14:56:43,RussTidwell,True,True,RT @atrupar: Definitely the guy you want in ch...,Hours after the President departed for Florida...,NaN,NaN,NaN,NaN,1.32328e+18,0,0.0,0.0,0.0,1.323241e+18
1,2020-11-02 14:56:44,HectorPernia6,True,False,RT @ConElMazoDando: China detecta rastros de C...,NaN,NaN,NaN,NaN,NaN,1.32328e+18,0,0.0,0.0,0.0,1.323277e+18
2,2020-11-02 14:56:44,YaariNews,False,False,coronavirus in maharashtra: राज्याला मोठा दिला...,NaN,NaN,NaN,NaN,NaN,1.32328e+18,0,0.0,0.0,0.0,NaN
3,2020-11-02 14:56:47,FrankNied,False,False,https://t.co/zIx3ynsc9G #COVIDー19 #coronavirus,NaN,NaN,NaN,COVIDー19;coronavirus,NaN,1.32328e+18,0,0.0,0.0,0.0,NaN
4,2020-11-02 14:56:48,marianapsol,False,False,"Para as 160 mil famílias, o dia de #Finados po...",NaN,NaN,NaN,NaN,NaN,1.32328e+18,0,0.0,0.0,0.0,NaN

In [13]:
vaccine = vaccine_file.reindex(index=order_by_index(vaccine_file.index, index_natsorted(vaccine_file['user'])))
mask = mask_file.reindex(index=order_by_index(mask_file.index, index_natsorted(mask_file['user'])))

In [14]:
mask.shape

TypeError: 'tuple' object is not callable